### PR TITLE
Fix codegen for FutureType.Result() method

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Replace future.Done() with future.DoneWithContext() as the former was
deprecated and has been removed in v12.0.0 of go-autorest.
Update vendored dependencies.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Azure/go-autorest/issues/388

**Comment by vladbarosan** [comment]
will this fix https://github.com/Azure/azure-sdk-for-go/issues/4579?

**Comment by jhendrixMSFT** [comment]
Yep it's a dupe of 388.

**Comment by fearthecowboy** [comment]
# 🤖 AutoRest automatic publish job 🤖
## success (version: 2.1.130)

**Pull request merged**
