### PR TITLE
Skip duplicate entry when aggregating allOf

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Some cases M4 does this for us.  In this case, we do it.
Added test to ensure coverage.
Bump version for next release.

### CODE REVIEW

**Review by seankane-msft — COMMENTED** [review]
When are there duplicates ? Is there an example of how this changes generated code ?

**Comment by jhendrixMSFT** [comment]
There are two cases for duplicates.  First is parent-child which M4 handles for us.  These already exist in various swaggers.  Second is siblings which M4 does not handle.  I added this in alias.json; `GeoJsonObject` and `GeoJsonFeatureData` now both have a duplicate `id` property.

**Comment by jhendrixMSFT** [comment]
As to how it changes the generated code.  Without this fix, `GeoJsonFeature` ended up with two fields `ID *string` which is broken.

**Comment by seankane-msft** [comment]
Ahhh gotcha. Thanks for the explanation, LGTM.

**Review by seankane-msft — APPROVED** [review]

**Pull request merged**
