### PR TITLE
Update azcore version

### PR DESCRIPTION
**Pull request by chlowell**
We need to ship this ASAP to prevent Component Governance flagging new libraries for an indirect CVE.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
You'll need to `rush regenerate` and `rush tspcompile` to regenerate the world. You might also need to `rush modtidy` after.

**Comment by chlowell** [comment]
Should `rush regenerate` also regenerate the baseline for `autorest.gotest`?

**Comment by jhendrixMSFT** [comment]
No, and it looks like those mock modules use very old versions. Might be best to revert that part of the change and let @tadelesh update autorest.gotest separately as I don't understand all the nuance of making changes there.

**Comment by jhendrixMSFT** [comment]
Can you also update the changelog for the tsp emitter to include a note about updating the minimum version of `azcore`? You might need to rebase after my recent merge.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
