### PR TITLE
Export response types when clients aren't

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Response types were inadvertently not being exported when exporting
clients is disabled.

### CODE REVIEW

**Comment by chlowell** [comment]
I feel like I'm missing something obvious here--why would someone want to export these types but not the client?

**Comment by chlowell** [comment]
I feel like I'm missing something obvious here--why would someone want to export these types but not the client?

**Comment by jhendrixMSFT** [comment]
For data-plane, the default is to not export the clients but export everything else.  The idea was that there would be hand-written clients that leverage the internal, generated ones, and all of the other types would be exported as-is.

The response types were being inadvertently not exported due to the clients being renamed before they were synthesized.

**Comment by chlowell** [comment]
Ah, I see. A handwritten client would be able to use the generated one provided they were in the same package, and the generated models would be exported to applications. Would we really ship a module like that? Sounds like DPG 😄

**Review by chlowell — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
It's currently what we're doing for `azblob` with limited success.  The path we took for `aztables` and key vault works much better.

**Pull request merged**
