### PR TITLE
Tiny import bug

### PR DESCRIPTION
**Pull request by mcardosos**
PTAL @jhendrixMSFT @marstr @vladbarosan 
Shows when generating from the `visualstudio` swagger.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
How did this not fail CI?

**Comment by jhendrixMSFT** [comment]
Ah this wasn't caught because the LRO tests aren't being run.  :(  Can you please update https://github.com/Azure/autorest.go/blob/master/test/src/tests/runner.go to include them in this PR?

**Comment by mcardosos** [comment]
@jhendrixMSFT There is a test that is not passing :(

**Comment by mcardosos** [comment]
Fixed test with this...
https://github.com/Azure/autorest.testserver/blob/c2e517f71d6a18a8ae5ec90aa2224a2354090bb8/routes/lros.js#L807

**Pull request merged**
