### PR TITLE
Change the way that we recognize a package as preview

### PR DESCRIPTION
**Pull request by ArcturusZhang**
This PR makes those tags that contains at least one preview swagger as a preview package.

Previously, a preview package is forced when all of the swaggers within a tag are preview.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Out of interest will this also catch services which release preview versions in stable API's? Using Networking & AKS as examples

**Comment by ArcturusZhang** [comment]
This will ensure that if a go package is generated from several swaggers and there is at least one swagger is preview, the go package will be marked as preview.

Previously we do not check this unless a set of swaggers are all preview.

**Comment by jhendrixMSFT** [comment]
Have you tried building the SDK with this change?  Do any packages now fail to build?

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT I am running a full scan of the swagger repo to see how many readme files need modifying. I will post the result here soon

**Comment by jhendrixMSFT** [comment]
Given our reliance on this and how much we're iterating on it I think it would be wise to add tests to cover this scenario in CI.

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT I open a PR to fix the bad output-folders: https://github.com/Azure/azure-rest-api-specs/pull/10842, you could get the list in the file changes.

**Comment by ArcturusZhang** [comment]
> Given our reliance on this and how much we're iterating on it I think it would be wise to add tests to cover this scenario in CI.

Could you please be more specific on this?

**Comment by jhendrixMSFT** [comment]
Unit tests for the detection of preview packages.  I assume it's something run manually, likely building the entire SDK.  Would be great to have something that runs as part of CI (can be a separate PR).

**Comment by fearthecowboy** [comment]
# 🤖 AutoRest automatic publish job 🤖
## success (version: 2.1.157)

**Pull request merged**
