### PR TITLE
Revert "Refactor codegen for long-running operations. (#39)"

### PR DESCRIPTION
**Pull request by marstr**
This reverts commit efe21ddebd63e15e5589f4b25a03ff9eb9168c9b.

This change should only be in the `breaking` branch, not `master` yet.

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by marstr** [comment]
I think there was timing issue here, and #39 got pulled into the wrong branch. I've already pulled `breaking` to include the reverted change :)

**Comment by mcardosos** [comment]
Is there a PR with LRO's changes on the way for breaking branch?

**Comment by marstr** [comment]
> @mcardosos says:
Is there a PR with LRO's changes on the way for breaking branch?

Nope, it's already there. Go check it out :)

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Pull request merged**
