### PR TITLE
Imporve the preview check logic

### PR DESCRIPTION
**Pull request by ArcturusZhang**
1. Now also throw exception when stable swaggers were outputed to preview directory
1. Add a new option `is-profile`, if assigned to true, the preview-chk logic will be skipped in this autorest task. This is serving a profile-targeting tag in readme.go.md

### CODE REVIEW

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT could you please have a review on this?

**Comment by jhendrixMSFT** [comment]
@ArcturusZhang have you tested this locally?  Asking since CI is currently broken and I don't have time to fix it at present.

**Comment by ArcturusZhang** [comment]
Hi @jhendrixMSFT 
I have tested locally in the following scenarios:
1. A tag with preview swagger but `output-folder` not in the preview subdirectory: will throw exception
1. A tag without preview swaggers but `output-folder` in the preview subdirectory: will throw exception
1. A tag with preview swagger but `output-folder` in the preview subdirectory: will not throw exception
1. A tag without preview swaggers but `output-folder` not in the preview subdirectory: will not throw exception
1. A tag with preview swagger, `output-folder` in the preview subdirectory and `is-profile=true`: will not throw exception

**Comment by fearthecowboy** [comment]
# 🤖 AutoRest automatic publish job 🤖
## success (version: 2.1.155)

**Pull request merged**
