### PR TITLE
Add pipeline for publishing dev builds of typespec-go

### PR DESCRIPTION
**Pull request by jhendrixMSFT**

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
@benbp does this pipeline need to be manually created or can we use prepare pipelines?

**Review by chlowell — APPROVED** [review]

**Comment by benbp** [comment]
@jhendrixMSFT we'll need to create one. Can you link me to some of the other publish pipelines?

**Comment by jhendrixMSFT** [comment]
Here's the one for publishing autorest.go to npmjs.org https://dev.azure.com/azure-sdk/internal/_build?definitionId=2214

I can't find the one for publishing beta builds though. I know we had this at one point as I can see old beta builds ([example](https://github.com/Azure/autorest.go/releases/tag/v4.0.0-20200728.1)). IIRC the pipeline for beta builds only published the artifacts to github and not npmjs.org.

**Comment by benbp** [comment]
@jhendrixMSFT to start https://dev.azure.com/azure-sdk/internal/_build/index?definitionId=6686&_a=completed

**Comment by jhendrixMSFT** [comment]
Thanks!

**Pull request merged**
