### PR TITLE
[Track 2] fix a comment for pagers

### PR DESCRIPTION
**Pull request by ArcturusZhang**
Found a warning from GoLand and hence I made this fix

### CODE REVIEW

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
You need to run `rush regenerate` to rebuild all of the test cases with the updated codegen.

**Comment by ArcturusZhang** [comment]
> You need to run `rush regenerate` to rebuild all of the test cases with the updated codegen.

thank you! That is the command. I tried `npm run generate-tests` and got a lot of errors.

**Comment by ArcturusZhang** [comment]
I get a lot of errors like this:
```
stderr: FATAL: YAMLException: unknown tag !<!AnyObjectSchema> in "code-model-v4.yaml" (16581:3)

 16578 |           name: AnyObject
 16579 |           description: Any object
 16580 |       protocol: !Protocols {}
 16581 |   dateTimes:
-----------^
 16582 |     - !DateTimeSchema &ref_1293
 16583 |       type: date-time
  Error: Plugin go-transform reported failure.

exec error: Error: Command failed: autorest --use=. https://raw.githubusercontent.com/Azure/azure-rest-api-specs/228cf296647f6e41182cee7d1a403990e6a8fe3c/specification/network/resource-manager/readme.md --tag=package-2020-03 --file-prefix="zz_generated_" --modelerfour.lenient-model-deduplication --license-header=MICROSOFT_MIT_NO_VERSION --output-folder=test/network/2020-03-01/armnetwork --module=armnetwork --azure-arm=true
FATAL: YAMLException: unknown tag !<!AnyObjectSchema> in "code-model-v4.yaml" (16581:3)

 16578 |           name: AnyObject
 16579 |           description: Any object
 16580 |       protocol: !Protocols {}
 16581 |   dateTimes:
-----------^
 16582 |     - !DateTimeSchema &ref_1293
 16583 |       type: date-time
  Error: Plugin go-transform reported failure.
```
Is this normal?

**Comment by ArcturusZhang** [comment]
Yeah... it turns out it is abnormal - a lot of test files are deleted after I run `rush regenerate`.
I am running this on powershell in windows. Is this relevant?

**Comment by jhendrixMSFT** [comment]
Hmm, seems weird.
- `rush update`
- `rush build`
- `rush regenerate`

Does this work?

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
