### PR TITLE
Revert exclusion of unused models

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Due to limitations of OpenAPI, some cases can't be accurately described
like support for oneOf.  As a result, we can't reliably determine if a
model type really isn't used as some specs emulate the oneOf behavior.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Azure/autorest.go/issues/771

**Comment by chlowell** [comment]
The few of these models I checked truly aren't used by their respective clients. Naively, it seems like ModelerFour could know a type is never used, but I take it that's impossible in general because ModelerFour is restricted to OpenAPI semantics? How can we be certain an error type is unused?

**Comment by jhendrixMSFT** [comment]
After the `oneOf` conversation I've been wondering the same thing.  While I suppose it seems unlikely that `oneOf` would be used for the error case, there's no reason why it couldn't be.  Makes me think that we should back out that portion of the change as well.
And frankly, we're talking about maybe a handful of types to omit out of dozens, if not more.  I don't think anybody will notice these vestigial types (they exist in track 1 and nobody has complained about them).

**Comment by chlowell** [comment]
Right, the impact is namespace pollution and wasted bytes. Worst case scenario is that one of these types disappears in a future version after being deleted from the swagger (which seems like the right fix) but an application somewhere took a dependency on that type despite not being able to use it with the associated client--seems pretty unlikely 😆

It would be nice for autorest to identify unused types though, if only to warn about swagger cruft.

**Review by chlowell — APPROVED** [review]

**Pull request merged**
